version: '3.7'

services:

  mongo-dump:
    image: ovski/ansible:v2.7.8
    volumes:
      - /tmp/mongo_dumps:/var/folder/mongo_dumps
      - ./:/var/www/ansible/playbooks/mongo-dump
    command: >
      ansible-playbook /var/www/ansible/playbooks/mongo-dump/main.yml
        -e "mongo_dumps_target_folder=/var/folder/mongo_dumps"
        -e "prune=yes"
        -e "db_port=27017"
        -e "db_host=mongo.domain.org"
        -e "db_name=mongo_db_name"
    environment:
      - ANSIBLE_HOST_KEY_CHECKING=False
    networks:
      - mongo_container_network

networks:

  mongo_container_network:
    external: true
